language: node_js
node_js:
  - "8.9.1"
os:
  - linux
  - osx
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: eff7f343aefb4a9f960c9f558a2a45cba92c56244f589cd37838a6b46c890557
osx_image: xcode8
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
after_script: 
  - npm run codeclimate
